config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tweets, only: [:index, :new, :create, :show] do
    resources :outputs, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/output.rb
class Output < ApplicationRecord
  validates :review, :youtube_url, presence: true
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, presence: true
  
  belongs_to :user
  has_many :outputs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :outputs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/outputs_controller.rb
class OutputsController < ApplicationController

  def new
    @output = Output.new
  end

  def create
    @output = Output.create(output_params)
    if @output.save
      redirect_to tweet_path(@output.tweet.id), notice: "投稿完了です!"
    else
      flash.now[:alert] = "メッセージを入力してください!"
      render template: "outputs/new"
    end
  end

  private
  def output_params
    params.require(:output).permit(:review, :youtube_url).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(8)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to root_path, notice: "ツイート完了!"
    else
      flash.now[:alert] = "メッセージを入力してください!"
      render template: "tweets/new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @output = Output.new
    @outputs = @tweet.outputs.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  private
  def tweet_params
    params.require(:tweet).permit(:text).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_flash.html.haml
.notifications
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0", name: "viewport"}
    %title MusicQuest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render partial: 'layouts/flash'
    .header{ id: "fixed" }
      .header__bar-row
        = link_to root_path, class: "header__bar-row--title" do
          Music Quest
        - if user_signed_in?
          .header__bar-row__right
            = link_to destroy_user_session_path, method: :delete, class: "header__bar-row__right__item" do
              ログアウト
            = link_to new_tweet_path, class: "header__bar-row__right__item" do
              曲を探す
            .header__bar-row__right__item
              .header__bar-row__right__item--greeting_message
                = "こんにちは"
              = icon('fas fa','user-circle')
              = current_user.nickname+" さん"
        - else
          .header__bar-row__right
            = link_to new_user_session_path, class: "header__bar-row__right__item" do
              ログイン
            = link_to new_user_registration_path, class: "header__bar-row__right__item" do
              新規登録
    = yield

app/views/outputs/new.html.haml
.output_contents
  .output_contents__content
    = form_for [@tweet, @output], url: tweet_outputs_path, class: "output_contents__content__form" do |f|
      %h5
      .output_contents__content__form__title1 コメント
      = f.text_area :review, placeholder: "例:僕が高校生の時によく聴いてました。春がきてから梅雨に入るまで聴くとなお良いです！" , rows: "10", class: "output_contents__content__form__title1--review"
      .output_contents__content__form__title2 YouTubeURL
      = f.text_field :youtube_url, placeholder: "youtube_url" , rows: "1", class: "output_contents__content__form__title2--url"
      = f.submit "投稿する", class: "output_contents__content__form__title2--btn"
  .output_contents__guide
    .output_contents__guide__guide1-content
      %p 利用時に注意すること
      %ul
        相手に不快を与える行為はしないようお願いします。
        %li 不適切な表現が含まれている動画を投稿しないこと(音楽とは全く関係のない動画)
        %li ユーザーへの荒らし・誹謗中傷・いたずら行為
        %li その他、運営者が不適切と判断したもの
    %p 投稿方法
    .output_contents__guide__guide2-content
      .output_contents__guide__guide2-content__title
        = "1.共有用のurlからコピペする方法"
      .output_contents__guide__guide2-content__bottom
        = video_tag 'sample.mp4', controls: '', width: '500px' ,height: '300px', class: 'output_contents__guide__guide2-content__bottom--gif'

    .output_contents__guide__guide3-content
      .output_contents__guide__guide3-content__title
        = "2.直接URLからコピペする方法。"
      .output_contents__guide__guide3-content__bottom
        = image_tag 'sample3.jpg', width: '600px',height: '400px', class: 'output_contents__guide__warning__title--img'
        %ul
          %li
            ※ 「&t=」または「&list=」から始まるコード(赤枠)はペーストあと動画が再生されないのでご注意ください。 ※
          %li
            = image_tag 'sample.png', height: '35px', class: 'output_contents__guide__warning__title--img'
          %li
            = image_tag 'sample2.png', height: '35px', class: 'output_contents__guide__warning__title--img'

app/views/tweets/index.html.haml
.top_contents
  .top_contents__topImage
    = image_tag asset_path('a0046233_011610.jpg'), class: "top_contents__topImage--image"
  .top_contents__title
    最新のツイート一覧
  .top_contents__tweet_contents
    - @tweets.each do |tweet|
      .top_contents__tweet_contents__tweet_content
        .top_contents__tweet_contents__tweet_content--body
          = simple_format(tweet.text)
        .top_contents__tweet_contents__tweet_content__bottom
          .top_contents__tweet_contents__tweet_content__bottom__username
            = icon('fas fa','user-circle', class: "top_contents__tweet_contents__tweet_content__bottom__username--icon")
            = tweet.user.nickname
          = link_to tweet_path(tweet), method: :get, class: "top_contents__tweet_contents__tweet_content__bottom__comment" do
            おしえて！
          .top_contents__tweet_contents__tweet_content__bottom__count
            = icon('fas fa', 'comment-alt', class: 'top_contents__tweet_contents__tweet_content__bottom__count--icon')
            = "#{tweet.outputs.length}"
= paginate(@tweets)

app/views/tweets/new.html.haml
.form_content
  = form_for [@tweet] do |f|
    %h1 曲を探そう！
    .input_box
      = f.text_area :text, class: 'input_box__text', placeholder: '例: 春を感じるJ-POPソング探してます!,洋楽でテンション上がる曲知ってる人!etc...', rows: "10"
      = f.submit 'さがす!', class: 'input_box__submit_btn'

app/views/tweets/show.html.haml
.tweet_contents
  .tweet_content
    .tweet_content__top
      .tweet_content__top--body
        = simple_format(@tweet.text)
    .tweet_content__bottom
      .tweet_content__bottom--name
        = @tweet.user.nickname
      - if user_signed_in? && current_user.id
        .tweet_content__bottom__outputNew
          = link_to "曲を投稿する", new_tweet_output_path(@tweet), class: "tweet_content__bottom__outputNew--btn"
      - else
        .tweet_content__bottom--warning
          曲を投稿したい方はログインしよう!
  .output_content
    .output_content__title
      あなたへのおすすめの曲
    - @outputs.each do |output|
      .output_content__body
        .output_content__body__left
        %iframe{allow: "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture", allowfullscreen: "", frameborder: "0", height: "315", src: "https://www.youtube.com/embed/#{output.youtube_url.last(11)}", width: "560", class: "output_content__body__left--youtube_container"}

        .output_content__body__right
          .output_content__body__right__name
            = icon('fas fa','user-circle', class: "output_content__body__right__name--icon")
            = "#{output.user.nickname}さんのコメント"

          .output_content__body__right__review
            = output.review
= paginate(@outputs)